package com.teya.agent.voice.speaker

import kotlinx.serialization.json.*
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.PI
import kotlin.math.sin

/**
 * Validates [Fbank]'s output against a reference fixture (`fbank_fixture.json`) generated by the
 * real Python `kaldi_native_fbank` library (the same one used during the Phase 0 spike) on an
 * identical, closed-form synthetic signal -- see `docs/experiments.md` / the plan for how the
 * fixture was produced. This is the correctness check for the one part of the speaker-ID feature
 * with genuine hand-written-DSP risk: if the framing/windowing/mel-filter math is subtly wrong,
 * embeddings would be silently degraded (not crash), so numeric agreement with a known-correct
 * reference implementation is the only real evidence this is right.
 */
class FbankTest {

    /** Regenerates the exact same synthetic signal the Python fixture was built from. */
    private fun referenceSignal(sampleRate: Int, numSamples: Int): FloatArray {
        val i = DoubleArray(numSamples) { it.toDouble() }
        val signal = DoubleArray(numSamples) { n ->
            3000.0 * sin(2 * PI * 440.0 * i[n] / sampleRate) +
                1500.0 * sin(2 * PI * 1200.0 * i[n] / sampleRate) +
                500.0 * sin(2 * PI * 3000.0 * i[n] / sampleRate) +
                200.0 * sin(2 * PI * 4321.0 * i[n] / sampleRate + 0.37 * sin(2 * PI * 17.0 * i[n] / sampleRate))
        }
        // Mirrors the Python fixture: clip to int16 range, round-trip through int16, then back to
        // float32 in [-1, 1] -- matching how real ShortArray mic audio gets converted in Kotlin.
        return FloatArray(numSamples) { n ->
            val clipped = signal[n].coerceIn(-32768.0, 32767.0)
            val asInt16 = clipped.toInt().toShort()
            asInt16 / 32768.0f
        }
    }

    @Test
    fun compute_matchesPythonKaldiNativeFbankReference() {
        val json = Json { ignoreUnknownKeys = true }
        val fixtureText = javaClass.classLoader!!.getResourceAsStream("fbank_fixture.json")!!
            .bufferedReader().readText()
        val fixture = json.parseToJsonElement(fixtureText).jsonObject

        val sampleRate = fixture["sample_rate"]!!.jsonPrimitive.int
        val numInputSamples = fixture["num_input_samples"]!!.jsonPrimitive.int
        val expectedNumFrames = fixture["num_frames"]!!.jsonPrimitive.int
        val expectedFeatDim = fixture["feat_dim"]!!.jsonPrimitive.int
        val sampleFramesRaw = fixture["sample_frames_raw"]!!.jsonObject

        val signal = referenceSignal(sampleRate, numInputSamples)
        val fbank = Fbank(sampleRate = sampleRate)
        val frames = fbank.compute(signal)

        assertEquals("frame count must match the reference implementation", expectedNumFrames, frames.size)
        assertEquals("feature dim must match the reference implementation", expectedFeatDim, frames[0].size)

        for ((indexStr, expectedValues) in sampleFramesRaw) {
            val frameIndex = indexStr.toInt()
            val expected = expectedValues.jsonArray.map { it.jsonPrimitive.float }
            val actual = frames[frameIndex]
            for (bin in expected.indices) {
                val diff = kotlin.math.abs(actual[bin] - expected[bin])
                assertTrue(
                    "frame $frameIndex bin $bin: expected ${expected[bin]}, got ${actual[bin]} (diff=$diff)",
                    diff < 0.05f,
                )
            }
        }
    }
}
